[".oh-my-zsh"]
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
exact = false
stripComponents = 1
refreshPeriod = "168h"
[".config/macos-terminal-themes"]
type = "git-repo"
url = "git@github.com:lysyi3m/macos-terminal-themes.git"
refreshPeriod = "168h"
[".config/nvim"]
type = "archive"
url = "https://github.com/LazyVim/starter/archive/refs/heads/main.tar.gz"
stripComponents = 1
exact = false
