[".oh-my-zsh"]
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
[".config/macos-terminal-themes"]
type = "git-repo"
url = "https://github.com/lysyi3m/macos-terminal-themes.git"
refreshPeriod = "168h"
[".config/nvim"]
type = "git-repo"
url = "https://github.com/LazyVim/starter"
